import { DocumentEngine } from './engine/DocumentEngine';
import { ExportEngine } from './engine/ExportEngine';
import JSZip from 'jszip';

/**
 * DocumentRenderer Facade
 * Provides a unified entry point for generating, exporting, and rendering documents.
 * Ensures DOCX and PDF flows share layout and metadata.
 */
export const DocumentRenderer = {
  /**
   * Universal exporter to compile and download DOCX files.
   */
  async exportDocx(type, base64, questions, qtypes, payload) {
    let arrayBuffer;

    if (type === 'docx' && base64) {
      // DOCX Mode: base64 is already the fully compiled DOCX binary generated by DocumentEngine in Step3!
      const binaryString = atob(base64);
      const len = binaryString.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      arrayBuffer = bytes.buffer;
    } else {
      // PDF Template or Default Mode: Generate standard formatted DOCX template programmatically
      const jszip = new JSZip();
      
      // Standard [Content_Types].xml
jszip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`);

      // Standard relationships file
      jszip.file("_rels/.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`);

      // Document body with metadata and the {{QUESTION_PAPER}} tag
      jszip.file("word/document.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:pPr><w:jc w:val="center"/></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:t>${payload.schoolName || 'Delhi Public School, Dwarka'}</w:t></w:r>
    </w:p>
    <w:p>
      <w:pPr><w:jc w:val="center"/></w:pPr>
      <w:r><w:rPr><w:sz w:val="22"/></w:rPr><w:t>${payload.schoolAddress || ''}</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:jc w:val="center"/></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="26"/></w:rPr><w:t>${payload.examName || ''}</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:r><w:rPr><w:b/></w:rPr><w:t>Subject: ${payload.subject || ''}   |   Class: Grade ${payload.grade || ''}</w:t></w:r>
    </w:p>
    <w:p>
      <w:r><w:rPr><w:b/></w:rPr><w:t>Time Allowed: ${payload.duration || ''}   |   Max Marks: ${payload.maxMarks || ''}</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:r><w:rPr><w:i/></w:rPr><w:t>General Instructions: All questions are compulsory. Marks for each question are shown on the right. Write neatly and show your working where needed.</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:r><w:t>{{QUESTION_PAPER}}</w:t></w:r>
    </w:p>
    <w:p/>
    <w:p>
      <w:pPr><w:jc w:val="center"/></w:pPr>
      <w:r><w:rPr><w:sz w:val="18"/></w:rPr><w:t>${payload.footerText || 'Confidential Examination Paper'}</w:t></w:r>
    </w:p>
  </w:body>
</w:document>`);

      const docxTemplateBuffer = await jszip.generateAsync({ type: "arraybuffer" });
      
      // Inject questions into standard in-memory template DOM XML directly
      arrayBuffer = await DocumentEngine.generateDocx(docxTemplateBuffer, questions, qtypes);
    }

    ExportEngine.downloadDocx(arrayBuffer, payload.examName);
  },

  /**
   * Universal exporter to compile and download PDF files.
   */
  async exportPdf(type, base64, examName, fallbackTrigger) {
    if (type === 'pdf' && base64) {
      const binaryString = atob(base64);
      const len = binaryString.length;
      const bytes = new Uint8Array(len);
      for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }
      ExportEngine.downloadPdf(bytes.buffer, examName);
    } else {
      if (fallbackTrigger) {
        await fallbackTrigger();
      }
    }
  }
};

export default DocumentRenderer;
